// Code generated by mockery v2.5.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Logger is an autogenerated mock type for the Logger type
type Logger struct {
	mock.Mock
}

// Error provides a mock function with given fields: err
func (_m *Logger) Error(err error) {
	_m.Called(err)
}

// Warn provides a mock function with given fields: err
func (_m *Logger) Warn(err error) {
	_m.Called(err)
}
