// Code generated by "stringer -type=errType"; DO NOT EDIT.

package errors

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown-1]
	_ = x[Internal-2]
	_ = x[Validation-3]
	_ = x[InputBody-4]
	_ = x[Duplicate-5]
	_ = x[Unauthenticated-6]
	_ = x[Unauthorized-7]
	_ = x[Empty-8]
	_ = x[NotFound-9]
	_ = x[MaximumAttempts-10]
	_ = x[SubscriptionExpired-11]
	_ = x[DownstreamDependencyTimedout-12]
}

const _errType_name = "UnknownInternalValidationInputBodyDuplicateUnauthenticatedUnauthorizedEmptyNotFoundMaximumAttemptsSubscriptionExpiredDownstreamDependencyTimedout"

var _errType_index = [...]uint8{0, 7, 15, 25, 34, 43, 58, 70, 75, 83, 98, 117, 145}

func (i errType) String() string {
	i -= 1
	if i < 0 || i >= errType(len(_errType_index)-1) {
		return "errType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _errType_name[_errType_index[i]:_errType_index[i+1]]
}
